#!/usr/bin/env bash
set -euo pipefail

PACKAGE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "$PACKAGE_ROOT/.." && pwd -P)"
APP="$REPO_ROOT/build/Agent Runtime.app"
CONTENTS="$APP/Contents"
MACOS="$CONTENTS/MacOS"
RESOURCES="$CONTENTS/Resources"
RUNTIME="$RESOURCES/runtime"
APP_ICON="$PACKAGE_ROOT/AppBundle/Resources/AppIcon.png"
NOTIFICATION_SOUND="$PACKAGE_ROOT/AppBundle/Resources/notification.mp3"

[[ -d "$REPO_ROOT/.venv" && -x "$REPO_ROOT/.venv/bin/python" ]] \
  || { echo "PACKAGE ERROR: checkout .venv is required to package the installed Runtime" >&2; exit 2; }
[[ -f "$REPO_ROOT/agent_runtime/server.py" ]] \
  || { echo "PACKAGE ERROR: checkout agent_runtime payload is incomplete" >&2; exit 2; }
[[ -f "$APP_ICON" ]] \
  || { echo "PACKAGE ERROR: approved application icon is missing" >&2; exit 2; }
[[ -f "$NOTIFICATION_SOUND" ]] \
  || { echo "PACKAGE ERROR: approved notification sound is missing" >&2; exit 2; }

/usr/bin/xcrun swift build --package-path "$PACKAGE_ROOT" -c release
BIN_DIR="$(/usr/bin/xcrun swift build --package-path "$PACKAGE_ROOT" -c release --show-bin-path)"
BINARY="$BIN_DIR/AgentRuntimeMenuBar"
[[ -x "$BINARY" ]] || { echo "PACKAGE ERROR: missing AgentRuntimeMenuBar binary" >&2; exit 2; }

rm -rf "$APP"
mkdir -p "$MACOS" "$RESOURCES" "$RUNTIME/agent_runtime"
cp "$PACKAGE_ROOT/AppBundle/Info.plist" "$CONTENTS/Info.plist"
cp "$BINARY" "$MACOS/AgentRuntimeMenuBar"
cp "$APP_ICON" "$RESOURCES/AppIcon.png"
cp "$NOTIFICATION_SOUND" "$RESOURCES/notification.mp3"
# Release the executable without checkout-specific Swift debug/object paths.
# Re-sign below after this deterministic packaging transformation.
/usr/bin/strip -S "$MACOS/AgentRuntimeMenuBar"

# The installed Runtime receives a private copy of implementation bytes. No
# checkout path or credential pointer is written into the bundle; installed
# execution derives its configuration from the per-user Application Support
# file at runtime.
cp "$REPO_ROOT/start.sh" "$RUNTIME/start.sh"
find "$REPO_ROOT/agent_runtime" -maxdepth 1 -type f -name '*.py' -exec cp '{}' "$RUNTIME/agent_runtime/" \;
# Dereference the checkout venv's interpreter links so the installed payload
# owns its executable bytes rather than pointing back through a checkout link.
/bin/cp -R -L "$REPO_ROOT/.venv" "$RUNTIME/.venv"
chmod 755 "$RUNTIME/start.sh"
chmod 755 "$RUNTIME/.venv/bin/python"
# A production payload must not carry checkout-generated bytecode, activation
# helpers, or pip entry points whose metadata can retain source paths. The
# embedded interpreter only needs its executable, venv metadata, and installed
# site-packages.
find "$RUNTIME/.venv" -type d -name '__pycache__' -prune -exec rm -rf '{}' +
find "$RUNTIME/.venv" -type f -name '*.pyc' -delete
find "$RUNTIME/.venv/bin" -type f ! -name 'python' -delete
find "$RUNTIME/.venv/bin" -type l -delete
TMP_PYVENV="$RUNTIME/.venv/.pyvenv.cfg.$$"
grep -E '^(home|include-system-site-packages|version|executable) = ' \
  "$RUNTIME/.venv/pyvenv.cfg" > "$TMP_PYVENV"
mv -f "$TMP_PYVENV" "$RUNTIME/.venv/pyvenv.cfg"

RUNTIME_REVISION="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || true)"
[[ "$RUNTIME_REVISION" =~ ^[0-9a-f]{40}$ ]] \
  || { echo "PACKAGE ERROR: repository revision is unavailable" >&2; exit 2; }
START_SHA="$(/usr/bin/shasum -a 256 "$RUNTIME/start.sh" | /usr/bin/awk '{print $1}')"
SERVER_SHA="$(/usr/bin/shasum -a 256 "$RUNTIME/agent_runtime/server.py" | /usr/bin/awk '{print $1}')"
cat > "$RESOURCES/runtime-manifest.json" <<MANIFEST
{
  "schema": 1,
  "owner": "com.picmao.agent-runtime",
  "runtime_revision": "$RUNTIME_REVISION",
  "entrypoint": "runtime/start.sh",
  "python": "runtime/.venv/bin/python",
  "mcp_package": "runtime/agent_runtime",
  "start_sha256": "$START_SHA",
  "server_sha256": "$SERVER_SHA",
  "external_dependencies": ["official tunnel-client", "macOS launchd", "macOS system utilities"]
}
MANIFEST
chmod 600 "$RESOURCES/runtime-manifest.json"

/usr/bin/plutil -lint "$CONTENTS/Info.plist" >/dev/null
[[ "$(/usr/libexec/PlistBuddy -c 'Print :LSUIElement' "$CONTENTS/Info.plist")" == "true" ]] \
  || { echo "PACKAGE ERROR: LSUIElement must be true" >&2; exit 2; }
/usr/bin/codesign --force --deep --sign - "$APP" >/dev/null
/usr/bin/codesign --verify --deep --strict "$APP"

echo "$APP"
